import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <nav className="keep-navbar">
        <h2 className="keep-logo">IngeNotas</h2>

        <div className="keep-links">
          <Link href="/">Inicio</Link>
          <Link href="/notes">Notas</Link>
          <Link href="/login">Login</Link>
          <Link href="/register">Registro</Link>
          <Link href="/profile">Perfil</Link>
          <Link href="/admin">Admin</Link>
        </div>
      </nav>{children}</body>
    </html>
  );
}
